version: "3.8"

services:
  mc:
    image: adorabus/minecraft-forge:cliww
    ports:
      - 25565:25565
      # - 25575:25575 # RCON
      - 8999:8999 #cliww
    volumes:
      - /home/fox/mc-forge:/mc
    environment:
      forge_version: latest
      Xms: 6G
      Xmx: 6G
      cliww_limit: 200
      cliww_password: changeme
